name: Java CI with Maven for Jakarta EE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 2  # Timeout the entire job after 2 minutes

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 21 (for Jakarta EE project)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Build with Maven to create the WAR file
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      # Deploy the WAR file to Tomcat
#      - name: Deploy to Tomcat
#        run: |
#          echo "Deploying WAR file to Tomcat..."
#
#          # Define paths
#          TOMCAT_BIN_DIR=/usr/share/tomcat10/bin
#          TOMCAT_WEBAPPS_DIR=/var/lib/tomcat10/webapps
#          WAR_FILE=/home/ubuntu/actions-runner/_work/FE-Sandbox/FE-Sandbox/target/FE-sandbox-1.0-SNAPSHOT.war
#
#          # Stop Tomcat
#          $TOMCAT_BIN_DIR/shutdown.sh
#          echo "Stopped Tomcat"
#
#          # Deploy the WAR file
#          sudo cp $WAR_FILE $TOMCAT_WEBAPPS_DIR/
#          echo "WAR file copied to webapps/"
#
#
#          # Start Tomcat
#          sudo $TOMCAT_BIN_DIR/startup.sh
#          echo "Started Tomcat"
